eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/
server:
    port: 8084
spring:
    application:
        name: accountmanagement-service
