hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
management:
    info:
        git:
            mode: full
server:
    port: 8089
spring:
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            - id: telemetry-service
              uri: lb://telemetry-service
              predicates:
              - Path=/telemetry-service/**
              filters:
              - RewritePath=/telemetry-service/(?<segment>.*), /$\{segment}
