eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8081
spring:
    application:
        name: telemetry-service
